/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamManagementIndexRouteImport } from './routes/team-management/index'
import { Route as StageManagementIndexRouteImport } from './routes/stage-management/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamManagementIndexRoute = TeamManagementIndexRouteImport.update({
  id: '/team-management/',
  path: '/team-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageManagementIndexRoute = StageManagementIndexRouteImport.update({
  id: '/stage-management/',
  path: '/stage-management/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stage-management/': typeof StageManagementIndexRoute
  '/team-management/': typeof TeamManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stage-management' | '/team-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stage-management' | '/team-management'
  id: '__root__' | '/' | '/stage-management/' | '/team-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StageManagementIndexRoute: typeof StageManagementIndexRoute
  TeamManagementIndexRoute: typeof TeamManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-management/': {
      id: '/team-management/'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof TeamManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-management/': {
      id: '/stage-management/'
      path: '/stage-management'
      fullPath: '/stage-management'
      preLoaderRoute: typeof StageManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StageManagementIndexRoute: StageManagementIndexRoute,
  TeamManagementIndexRoute: TeamManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
