/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamManagementIndexRouteImport } from './routes/team-management/index'
import { Route as StageManagementIndexRouteImport } from './routes/stage-management/index'
import { Route as OffstageValuationIndexRouteImport } from './routes/offstage-valuation/index'
import { Route as MediaManagementIndexRouteImport } from './routes/media-management/index'
import { Route as JudgementIndexRouteImport } from './routes/judgement/index'
import { Route as AnnounceManagementIndexRouteImport } from './routes/announce-management/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamManagementIndexRoute = TeamManagementIndexRouteImport.update({
  id: '/team-management/',
  path: '/team-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageManagementIndexRoute = StageManagementIndexRouteImport.update({
  id: '/stage-management/',
  path: '/stage-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffstageValuationIndexRoute = OffstageValuationIndexRouteImport.update({
  id: '/offstage-valuation/',
  path: '/offstage-valuation/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaManagementIndexRoute = MediaManagementIndexRouteImport.update({
  id: '/media-management/',
  path: '/media-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgementIndexRoute = JudgementIndexRouteImport.update({
  id: '/judgement/',
  path: '/judgement/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnounceManagementIndexRoute = AnnounceManagementIndexRouteImport.update({
  id: '/announce-management/',
  path: '/announce-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/announce-management': typeof AnnounceManagementIndexRoute
  '/judgement': typeof JudgementIndexRoute
  '/media-management': typeof MediaManagementIndexRoute
  '/offstage-valuation': typeof OffstageValuationIndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/announce-management': typeof AnnounceManagementIndexRoute
  '/judgement': typeof JudgementIndexRoute
  '/media-management': typeof MediaManagementIndexRoute
  '/offstage-valuation': typeof OffstageValuationIndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/announce-management/': typeof AnnounceManagementIndexRoute
  '/judgement/': typeof JudgementIndexRoute
  '/media-management/': typeof MediaManagementIndexRoute
  '/offstage-valuation/': typeof OffstageValuationIndexRoute
  '/stage-management/': typeof StageManagementIndexRoute
  '/team-management/': typeof TeamManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announce-management'
    | '/judgement'
    | '/media-management'
    | '/offstage-valuation'
    | '/stage-management'
    | '/team-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announce-management'
    | '/judgement'
    | '/media-management'
    | '/offstage-valuation'
    | '/stage-management'
    | '/team-management'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/announce-management/'
    | '/judgement/'
    | '/media-management/'
    | '/offstage-valuation/'
    | '/stage-management/'
    | '/team-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnnounceManagementIndexRoute: typeof AnnounceManagementIndexRoute
  JudgementIndexRoute: typeof JudgementIndexRoute
  MediaManagementIndexRoute: typeof MediaManagementIndexRoute
  OffstageValuationIndexRoute: typeof OffstageValuationIndexRoute
  StageManagementIndexRoute: typeof StageManagementIndexRoute
  TeamManagementIndexRoute: typeof TeamManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-management/': {
      id: '/team-management/'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof TeamManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-management/': {
      id: '/stage-management/'
      path: '/stage-management'
      fullPath: '/stage-management'
      preLoaderRoute: typeof StageManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offstage-valuation/': {
      id: '/offstage-valuation/'
      path: '/offstage-valuation'
      fullPath: '/offstage-valuation'
      preLoaderRoute: typeof OffstageValuationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-management/': {
      id: '/media-management/'
      path: '/media-management'
      fullPath: '/media-management'
      preLoaderRoute: typeof MediaManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judgement/': {
      id: '/judgement/'
      path: '/judgement'
      fullPath: '/judgement'
      preLoaderRoute: typeof JudgementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announce-management/': {
      id: '/announce-management/'
      path: '/announce-management'
      fullPath: '/announce-management'
      preLoaderRoute: typeof AnnounceManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnnounceManagementIndexRoute: AnnounceManagementIndexRoute,
  JudgementIndexRoute: JudgementIndexRoute,
  MediaManagementIndexRoute: MediaManagementIndexRoute,
  OffstageValuationIndexRoute: OffstageValuationIndexRoute,
  StageManagementIndexRoute: StageManagementIndexRoute,
  TeamManagementIndexRoute: TeamManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
