/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamManagementIndexRouteImport } from './routes/team-management/index'
import { Route as StageManagementIndexRouteImport } from './routes/stage-management/index'
import { Route as PrizeManagementIndexRouteImport } from './routes/prize-management/index'
import { Route as OffstageManagementIndexRouteImport } from './routes/offstage-management/index'
import { Route as MediaManagementIndexRouteImport } from './routes/media-management/index'
import { Route as JudgementIndexRouteImport } from './routes/judgement/index'
import { Route as J23dgdfgeLinfh34IndexRouteImport } from './routes/j23dgdfge-linfh34/index'
import { Route as FoodCourtControlIndexRouteImport } from './routes/food-court-control/index'
import { Route as AnnounceManagementIndexRouteImport } from './routes/announce-management/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as JudgementSuccessRouteImport } from './routes/judgement/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamManagementIndexRoute = TeamManagementIndexRouteImport.update({
  id: '/team-management/',
  path: '/team-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const StageManagementIndexRoute = StageManagementIndexRouteImport.update({
  id: '/stage-management/',
  path: '/stage-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizeManagementIndexRoute = PrizeManagementIndexRouteImport.update({
  id: '/prize-management/',
  path: '/prize-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffstageManagementIndexRoute = OffstageManagementIndexRouteImport.update({
  id: '/offstage-management/',
  path: '/offstage-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaManagementIndexRoute = MediaManagementIndexRouteImport.update({
  id: '/media-management/',
  path: '/media-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgementIndexRoute = JudgementIndexRouteImport.update({
  id: '/judgement/',
  path: '/judgement/',
  getParentRoute: () => rootRouteImport,
} as any)
const J23dgdfgeLinfh34IndexRoute = J23dgdfgeLinfh34IndexRouteImport.update({
  id: '/j23dgdfge-linfh34/',
  path: '/j23dgdfge-linfh34/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodCourtControlIndexRoute = FoodCourtControlIndexRouteImport.update({
  id: '/food-court-control/',
  path: '/food-court-control/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnounceManagementIndexRoute = AnnounceManagementIndexRouteImport.update({
  id: '/announce-management/',
  path: '/announce-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgementSuccessRoute = JudgementSuccessRouteImport.update({
  id: '/judgement/success',
  path: '/judgement/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/judgement/success': typeof JudgementSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/announce-management': typeof AnnounceManagementIndexRoute
  '/food-court-control': typeof FoodCourtControlIndexRoute
  '/j23dgdfge-linfh34': typeof J23dgdfgeLinfh34IndexRoute
  '/judgement': typeof JudgementIndexRoute
  '/media-management': typeof MediaManagementIndexRoute
  '/offstage-management': typeof OffstageManagementIndexRoute
  '/prize-management': typeof PrizeManagementIndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/judgement/success': typeof JudgementSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/announce-management': typeof AnnounceManagementIndexRoute
  '/food-court-control': typeof FoodCourtControlIndexRoute
  '/j23dgdfge-linfh34': typeof J23dgdfgeLinfh34IndexRoute
  '/judgement': typeof JudgementIndexRoute
  '/media-management': typeof MediaManagementIndexRoute
  '/offstage-management': typeof OffstageManagementIndexRoute
  '/prize-management': typeof PrizeManagementIndexRoute
  '/stage-management': typeof StageManagementIndexRoute
  '/team-management': typeof TeamManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/judgement/success': typeof JudgementSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/announce-management/': typeof AnnounceManagementIndexRoute
  '/food-court-control/': typeof FoodCourtControlIndexRoute
  '/j23dgdfge-linfh34/': typeof J23dgdfgeLinfh34IndexRoute
  '/judgement/': typeof JudgementIndexRoute
  '/media-management/': typeof MediaManagementIndexRoute
  '/offstage-management/': typeof OffstageManagementIndexRoute
  '/prize-management/': typeof PrizeManagementIndexRoute
  '/stage-management/': typeof StageManagementIndexRoute
  '/team-management/': typeof TeamManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/judgement/success'
    | '/admin'
    | '/announce-management'
    | '/food-court-control'
    | '/j23dgdfge-linfh34'
    | '/judgement'
    | '/media-management'
    | '/offstage-management'
    | '/prize-management'
    | '/stage-management'
    | '/team-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/judgement/success'
    | '/admin'
    | '/announce-management'
    | '/food-court-control'
    | '/j23dgdfge-linfh34'
    | '/judgement'
    | '/media-management'
    | '/offstage-management'
    | '/prize-management'
    | '/stage-management'
    | '/team-management'
  id:
    | '__root__'
    | '/'
    | '/judgement/success'
    | '/admin/'
    | '/announce-management/'
    | '/food-court-control/'
    | '/j23dgdfge-linfh34/'
    | '/judgement/'
    | '/media-management/'
    | '/offstage-management/'
    | '/prize-management/'
    | '/stage-management/'
    | '/team-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JudgementSuccessRoute: typeof JudgementSuccessRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnnounceManagementIndexRoute: typeof AnnounceManagementIndexRoute
  FoodCourtControlIndexRoute: typeof FoodCourtControlIndexRoute
  J23dgdfgeLinfh34IndexRoute: typeof J23dgdfgeLinfh34IndexRoute
  JudgementIndexRoute: typeof JudgementIndexRoute
  MediaManagementIndexRoute: typeof MediaManagementIndexRoute
  OffstageManagementIndexRoute: typeof OffstageManagementIndexRoute
  PrizeManagementIndexRoute: typeof PrizeManagementIndexRoute
  StageManagementIndexRoute: typeof StageManagementIndexRoute
  TeamManagementIndexRoute: typeof TeamManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-management/': {
      id: '/team-management/'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof TeamManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-management/': {
      id: '/stage-management/'
      path: '/stage-management'
      fullPath: '/stage-management'
      preLoaderRoute: typeof StageManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prize-management/': {
      id: '/prize-management/'
      path: '/prize-management'
      fullPath: '/prize-management'
      preLoaderRoute: typeof PrizeManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offstage-management/': {
      id: '/offstage-management/'
      path: '/offstage-management'
      fullPath: '/offstage-management'
      preLoaderRoute: typeof OffstageManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-management/': {
      id: '/media-management/'
      path: '/media-management'
      fullPath: '/media-management'
      preLoaderRoute: typeof MediaManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judgement/': {
      id: '/judgement/'
      path: '/judgement'
      fullPath: '/judgement'
      preLoaderRoute: typeof JudgementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/j23dgdfge-linfh34/': {
      id: '/j23dgdfge-linfh34/'
      path: '/j23dgdfge-linfh34'
      fullPath: '/j23dgdfge-linfh34'
      preLoaderRoute: typeof J23dgdfgeLinfh34IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-court-control/': {
      id: '/food-court-control/'
      path: '/food-court-control'
      fullPath: '/food-court-control'
      preLoaderRoute: typeof FoodCourtControlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announce-management/': {
      id: '/announce-management/'
      path: '/announce-management'
      fullPath: '/announce-management'
      preLoaderRoute: typeof AnnounceManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judgement/success': {
      id: '/judgement/success'
      path: '/judgement/success'
      fullPath: '/judgement/success'
      preLoaderRoute: typeof JudgementSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JudgementSuccessRoute: JudgementSuccessRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnnounceManagementIndexRoute: AnnounceManagementIndexRoute,
  FoodCourtControlIndexRoute: FoodCourtControlIndexRoute,
  J23dgdfgeLinfh34IndexRoute: J23dgdfgeLinfh34IndexRoute,
  JudgementIndexRoute: JudgementIndexRoute,
  MediaManagementIndexRoute: MediaManagementIndexRoute,
  OffstageManagementIndexRoute: OffstageManagementIndexRoute,
  PrizeManagementIndexRoute: PrizeManagementIndexRoute,
  StageManagementIndexRoute: StageManagementIndexRoute,
  TeamManagementIndexRoute: TeamManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
