services:
  server:
    build:
      target: 'server'
      context: ../
      dockerfile: ./ops/Dockerfile
    restart: unless-stopped
    pull_policy: build
    environment:
      - ENV=$ENV
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - CORS_ENABLED_URLS=$CORS_ENABLED_URLS
      - TG_BOT_API_KEY=$TG_BOT_API_KEY
      - TG_CHANNEL_ID=$TG_CHANNEL_ID
    networks:
      - nginx-proxy

  client:
    pull_policy: build
    build:
      target: 'client'
      context: ../
      dockerfile: ./ops/Dockerfile
      args:
        - VITE_API_URL=$VITE_API_URL
    volumes:
      - /var/www/html/sahityotsav_management/client:/var/www/html

volumes:
  builds:

networks:
  nginx-proxy:
    external: true
